### ISSUE TITLE
Cannot start without issue "Component definition is missing display name  react/display-name"

### ISSUE THREAD

**Issue by Pryla** [app-generator/django-react-soft-dashboard#1]
Hi guys, great project but there seems to be a bug: I keep getting this error `Component definition is missing display name  react/display-name`for every component. Also: for :5000/api/ or any other route I keep getting a 404. What am I missing?

Cheers

**Comment by app-generator** [comment]
Hello @Pryla 

Please follow this set up: 

- Install or activate Nodejs `v14.15.0` via NVM
- start the API via Docker or manual build
- compile & start the React UI

The product is tested on Windows and Debian-like distros (Ubuntu).

In case the build is not successful, please reply with more information regarding your environment

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
