### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by B14ckFox** [app-generator/django-react-soft-dashboard#3]
Hi, 

cool project!

I'm struggling a bit by setting up the backend. 

I'm using windows and followed the instructions, but when I start the backend I got the following error message:

"The requested resource was not found on this server. "

Checked it via http://localhost:5000/api/

What is about the API do I need to add this somewhere or is this already considered for the fast setup. 

I have used the manual setup:
I have just followed instructions 1 to 5.  

Thanks

**Comment by app-generator** [comment]
Hello @BlackFox16 

The backend is not starting? 
If possible, please attach the runtime log of the API during requests. 

[AppSeed](https://appseed.us/) Support

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
