### ISSUE TITLE
Error on start project django-react-soft-dashboard

### ISSUE THREAD

**Issue by GustavoPiris** [app-generator/django-react-soft-dashboard#4]
I have downloaded the project from this repository https://github.com/app-generator/django-react-soft-dashboard
I've follow the documentation step by step, but when run yarn start it show me this error 

![imagen](https://github.com/app-generator/django-react-soft-dashboard/assets/8332139/180582e2-974d-486d-bf77-fff8fe6d756d)

**Comment by app-generator** [comment]
Hello @GustavoPiris 

Just tested the KIT and seems to work. Please provide the following:

- Node Version
- NPM Version
- YARN version (if used)
- Operating system

FYI, our cross tests are made with:

- Node `v16.15.0`
- Yarn & PMPM

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
