### ISSUE TITLE
CORS blocking permission request

### ISSUE THREAD

**Issue by Waterfountain10** [app-generator/django-react-soft-dashboard#6]
<img width="1456" alt="image" src="https://github.com/app-generator/django-react-soft-dashboard/assets/98282992/b49f0dd9-b073-4930-ba98-20aa17d957ef">

Access to XMLHttpRequest at 'http://localhost:5000/api/users/register' from origin 'http://127.0.0.1:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by app-generator** [comment]
Closing. Environmental issue.

**Comment by app-generator** [comment]
@Waterfountain10 ping us anytime for help.
https://appseed.us/support/
